services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=simple_blog_api
    api:
        build: ./
        image: docker.io/akhileshsonar/simple_blog_api
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PASSWORD=postgres_password
            - PGPORT=5432
            - POSTGRES_DB=simple_blog_api
        ports:
            - "3000:3000"