--Drop the tables
DROP TABLE files;
DROP TABLE word_counts;

-- Create a table to store results
CREATE TABLE files (line STRING);

--Loading data into files table
LOAD DATA LOCAL INPATH '/root/input.txt' INTO TABLE files;

--Count the number of words
CREATE TABLE word_counts AS
SELECT word, COUNT(word) AS wordCount FROM
(SELECT explode(split(line, ' ')) AS word FROM files) w
GROUP BY word
ORDER BY wordCount DESC;

--Display the results
SELECT * FROM word_counts