services:
    #Postgres database
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    #Redis database
    redis:
        image: redis
        command: ["redis-server", "--protected-mode", "no"]
    #Express API server
    api:
        build:
            context: ./server
        image: docker.io/suprajabhargavi/complex-api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    #React client
    client:
        build: ./client
        image: docker.io/suprajabhargavi/complex-client
    #Worker service
    worker:
        build: ./worker
        image: docker.io/suprajabhargavi/complex-worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    #Nginx service
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build: ./nginx
        ports:
            - "8082:80"
