services:
    redis-server:
        image: docker.io/redis
        volumes:
          - ./redis:/data
        command: ["redis-server", "--save", "1 1", "--protected-mode", "no"]
    node-app:
        restart: always
        build: ./
        image: docker.io/suprajabhargavi/visits
        ports:
            - "8081:8081"